DROP TABLE MOVIE;

CREATE TABLE MOVIE(
	CODE     NUMBER(4) CONSTRAINT PK_MOVIE_CODE PRIMARY KEY,
	TITLE    VARCHAR(50),
	PRICE    NUMBER(10),
	DIRECTOR VARCHAR(20),
	ACTOR    VARCHAR(20),
	POSTER   VARCHAR(1000),
	SYNOPSIS VARCHAR(3000)
);

CREATE SEQUENCE MOVIE_SEQ NOCACHE;

COMMENT ON COLUMN MOVIE.CODE IS '영화코드';
COMMENT ON COLUMN MOVIE.TITLE IS '영화제목';
COMMENT ON COLUMN MOVIE.PRICE IS '영화가격';
COMMENT ON COLUMN MOVIE.DIRECTOR IS '영화감독';
COMMENT ON COLUMN MOVIE.ACTOR  IS '영화배우';
COMMENT ON COLUMN MOVIE.POSTER IS '영화포스터';
COMMENT ON COLUMN MOVIE.SYNOPSIS IS '영화시놉시스';

INSERT INTO MOVIE
VALUES(MOVIE_SEQ.NEXTVAL,'베를린',10000,'류승완','하정우','movie1.jpg','거대한 국제적 음모가 숨겨진 운명의 도시 베를린');
INSERT INTO MOVIE
VALUES(MOVIE_SEQ.NEXTVAL,'박수건달',10000,'조진규','박신양,엄지원','movie2.jpg','건달로 사느냐, 무당으로 사느냐 그것이 문제로다');
INSERT INTO MOVIE
VALUES(MOVIE_SEQ.NEXTVAL,'레미제라블',10000,'톰 후퍼','휴 잭맨','movie3.jpg','빵 한조각을 훔친 죄로 19년의 감옥살이를 한 장발장');
INSERT INTO MOVIE
VALUES(MOVIE_SEQ.NEXTVAL,'7번방의 선물',9000,'이환경','류승룡, 갈소원','movie4.jpg','최악의 흉악범들이 모인 교도소 7번방에 이상한');

SELECT CODE, TITLE, PRICE, DIRECTOR, ACTOR, POSTER, SYNOPSIS
FROM   MOVIE;